addSbtPlugin("com.github.tkawachi" % "sbt-doctest" % "0.5.0")
addSbtPlugin("com.github.gseitz" % "sbt-release" % "1.0.4")
addSbtPlugin("com.jsuereth" % "sbt-pgp" % "1.0.1")
addSbtPlugin("org.xerial.sbt" % "sbt-sonatype" % "1.1")
addSbtPlugin("io.get-coursier" % "sbt-coursier" % "1.0.0-RC7")